package com.linonward.app.designsystem

import androidx.compose.ui.graphics.Color

// Generated by scripts/design-tokens.mjs from design/tokens.json. Do not edit.
internal object BrandColors {
  val Navy50 = Color(0xFFF2F7FE)
  val Navy100 = Color(0xFFE4EEFA)
  val Navy200 = Color(0xFFCEDEF2)
  val Navy300 = Color(0xFFB1C8E5)
  val Navy400 = Color(0xFF94B4DB)
  val Navy500 = Color(0xFF789FCE)
  val Navy600 = Color(0xFF5E83AF)
  val Navy700 = Color(0xFF44658E)
  val Navy800 = Color(0xFF27466B)
  val Navy900 = Color(0xFF03274D)
  val Navy950 = Color(0xFF00112D)
  val Teal50 = Color(0xFFECFAFA)
  val Teal100 = Color(0xFFD8F3F3)
  val Teal200 = Color(0xFFB9E7E6)
  val Teal300 = Color(0xFF8FD4D4)
  val Teal400 = Color(0xFF5DC4C4)
  val Teal500 = Color(0xFF0DB2B3)
  val Teal600 = Color(0xFF009596)
  val Teal700 = Color(0xFF007677)
  val Teal800 = Color(0xFF005557)
  val Teal900 = Color(0xFF003639)
  val Teal950 = Color(0xFF001B1F)

  val DestructiveLight = Color(0xFFE7000B)
  val DestructiveDark = Color(0xFFFF6467)
}

internal object DesignTokens {
  object Spacing {
  const val Xs = 6
  const val Sm = 8
  const val Md = 12
  const val Lg = 16
  const val Xl = 20
  const val Xxl = 24
  const val Xxxl = 28
  const val Xxxxl = 40
  }
  object Radius {
  const val Card = 12
  const val BrandMark = 14
  }
  object Size {
  const val BrandMark = 56
  const val PrimaryButtonMinimumHeight = 48
  const val ContentMaximumWidth = 560
  }
}
