import SwiftUI

// Generated by scripts/design-tokens.mjs from design/tokens.json. Do not edit.
extension Color {
  static let navy50 = Color(red: 242 / 255, green: 247 / 255, blue: 254 / 255)
  static let navy100 = Color(red: 228 / 255, green: 238 / 255, blue: 250 / 255)
  static let navy200 = Color(red: 206 / 255, green: 222 / 255, blue: 242 / 255)
  static let navy300 = Color(red: 177 / 255, green: 200 / 255, blue: 229 / 255)
  static let navy400 = Color(red: 148 / 255, green: 180 / 255, blue: 219 / 255)
  static let navy500 = Color(red: 120 / 255, green: 159 / 255, blue: 206 / 255)
  static let navy600 = Color(red: 94 / 255, green: 131 / 255, blue: 175 / 255)
  static let navy700 = Color(red: 68 / 255, green: 101 / 255, blue: 142 / 255)
  static let navy800 = Color(red: 39 / 255, green: 70 / 255, blue: 107 / 255)
  static let navy900 = Color(red: 3 / 255, green: 39 / 255, blue: 77 / 255)
  static let navy950 = Color(red: 0 / 255, green: 17 / 255, blue: 45 / 255)
  static let teal50 = Color(red: 236 / 255, green: 250 / 255, blue: 250 / 255)
  static let teal100 = Color(red: 216 / 255, green: 243 / 255, blue: 243 / 255)
  static let teal200 = Color(red: 185 / 255, green: 231 / 255, blue: 230 / 255)
  static let teal300 = Color(red: 143 / 255, green: 212 / 255, blue: 212 / 255)
  static let teal400 = Color(red: 93 / 255, green: 196 / 255, blue: 196 / 255)
  static let teal500 = Color(red: 13 / 255, green: 178 / 255, blue: 179 / 255)
  static let teal600 = Color(red: 0 / 255, green: 149 / 255, blue: 150 / 255)
  static let teal700 = Color(red: 0 / 255, green: 118 / 255, blue: 119 / 255)
  static let teal800 = Color(red: 0 / 255, green: 85 / 255, blue: 87 / 255)
  static let teal900 = Color(red: 0 / 255, green: 54 / 255, blue: 57 / 255)
  static let teal950 = Color(red: 0 / 255, green: 27 / 255, blue: 31 / 255)
  static let destructiveLight = Color(red: 231 / 255, green: 0 / 255, blue: 11 / 255)
  static let destructiveDark = Color(red: 255 / 255, green: 100 / 255, blue: 103 / 255)
  static let brandNavy = navy900
  static let brandTeal = teal500
}

enum DesignTokens {
  enum Spacing {
    static let xs: CGFloat = 6
    static let sm: CGFloat = 8
    static let md: CGFloat = 12
    static let lg: CGFloat = 16
    static let xl: CGFloat = 20
    static let xxl: CGFloat = 24
    static let xxxl: CGFloat = 28
    static let xxxxl: CGFloat = 40
  }
  enum Radius {
    static let card: CGFloat = 12
    static let brandMark: CGFloat = 14
  }
  enum Size {
    static let brandMark: CGFloat = 56
    static let primaryButtonMinimumHeight: CGFloat = 48
    static let contentMaximumWidth: CGFloat = 560
  }
}
