#!/usr/bin/env node

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const tokens = JSON.parse(await readFile(path.join(repositoryRoot, "design/tokens.json"), "utf8"));
const checkOnly = process.argv.includes("--check");
const notice = "Generated by scripts/design-tokens.mjs from design/tokens.json. Do not edit.";
const upperFirst = (value) => value.charAt(0).toUpperCase() + value.slice(1);
const safeName = (value) =>
  value.replace(/^2xl$/, "xxl").replace(/^3xl$/, "xxxl").replace(/^4xl$/, "xxxxl");
const snakeCase = (value) => value.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);
const kebabCase = (value) =>
  value
    .replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)
    .replace(/([a-z])([0-9])/g, "$1-$2");

function resolveColor(reference) {
  const value = reference.split(".").reduce((current, segment) => current?.[segment], tokens.color);
  if (typeof value !== "string" || !/^#[0-9A-F]{6}$/.test(value)) {
    throw new Error(`Invalid color reference: ${reference}`);
  }
  return value;
}

const colorEntries = Object.entries(tokens.color.ramp).flatMap(([family, ramp]) =>
  Object.entries(ramp).map(([step, hex]) => [`${upperFirst(family)}${step}`, hex]),
);

function dimensions(group, language) {
  return Object.entries(tokens[group])
    .map(([name, value]) => {
      const identifier = safeName(name);
      return language === "swift"
        ? `    static let ${identifier}: CGFloat = ${value}`
        : `  const val ${upperFirst(identifier)} = ${value}`;
    })
    .join("\n");
}

function generateAndroid() {
  const colors = colorEntries
    .map(([name, hex]) => `  val ${name} = Color(0xFF${hex.slice(1)})`)
    .join("\n");
  return `package com.linonward.app.designsystem

import androidx.compose.ui.graphics.Color

// ${notice}
internal object BrandColors {
${colors}

  val DestructiveLight = Color(0xFF${tokens.color.fixed.destructiveLight.slice(1)})
  val DestructiveDark = Color(0xFF${tokens.color.fixed.destructiveDark.slice(1)})
}

internal object DesignTokens {
  object Spacing {
${dimensions("spacing", "kotlin")}
  }
  object Radius {
${dimensions("radius", "kotlin")}
  }
  object Size {
${dimensions("size", "kotlin")}
  }
}
`;
}

function swiftColor(hex) {
  const [red, green, blue] = [hex.slice(1, 3), hex.slice(3, 5), hex.slice(5, 7)].map((value) =>
    Number.parseInt(value, 16),
  );
  return `Color(red: ${red} / 255, green: ${green} / 255, blue: ${blue} / 255)`;
}

function generateIOS() {
  const colors = colorEntries
    .map(
      ([name, hex]) =>
        `  static let ${name.charAt(0).toLowerCase() + name.slice(1)} = ${swiftColor(hex)}`,
    )
    .join("\n");
  return `import SwiftUI

// ${notice}
extension Color {
${colors}
  static let destructiveLight = ${swiftColor(tokens.color.fixed.destructiveLight)}
  static let destructiveDark = ${swiftColor(tokens.color.fixed.destructiveDark)}
  static let brandNavy = navy900
  static let brandTeal = teal500
}

enum DesignTokens {
  enum Spacing {
${dimensions("spacing", "swift")}
  }
  enum Radius {
${dimensions("radius", "swift")}
  }
  enum Size {
${dimensions("size", "swift")}
  }
}
`;
}

function harmonyColors(mode) {
  const harmonyNames = new Set([
    "pageBackground",
    "surface",
    "border",
    "textPrimary",
    "textSecondary",
    "textAccent",
  ]);
  const semantic = Object.entries(tokens.color.semantic[mode])
    .filter(([name]) => harmonyNames.has(name))
    .map(([name, reference]) => ({ name: snakeCase(name), value: resolveColor(reference) }));
  const fixed =
    mode === "light"
      ? [
          { name: "brand_navy", value: resolveColor("ramp.navy.900") },
          { name: "brand_teal", value: resolveColor("ramp.teal.500") },
          { name: "start_window_background", value: resolveColor("ramp.navy.900") },
        ]
      : [];
  return `${JSON.stringify({ color: [...fixed, ...semantic] }, null, 2)}\n`;
}

function cssColor(reference) {
  if (reference === "fixed.white") return "oklch(1 0 0)";
  if (reference.startsWith("fixed.")) return resolveColor(reference).toLowerCase();
  const [, family, step] = reference.split(".");
  return `var(--color-${family}-${step})`;
}

function generateWebCSS() {
  const ramps = Object.entries(tokens.color.cssRamp)
    .flatMap(([family, ramp]) =>
      Object.entries(ramp).map(([step, value]) => `  --color-${family}-${step}: ${value};`),
    )
    .join("\n");
  const nativeOnly = new Set([
    "pageBackground",
    "surface",
    "textPrimary",
    "textSecondary",
    "textAccent",
  ]);
  const semantic = (mode, indent = "  ") =>
    Object.entries(tokens.color.semantic[mode])
      .filter(([name]) => !nativeOnly.has(name))
      .map(([name, reference]) => `${indent}--${kebabCase(name)}: ${cssColor(reference)};`)
      .join("\n");
  const spacing = Object.entries(tokens.spacing)
    .map(([name, value]) => `  --lin-spacing-${safeName(name)}: ${value / 16}rem;`)
    .join("\n");

  return `/* ${notice} */
@theme {
${ramps}
}

:root {
  color-scheme: light dark;
${semantic("light")}
  --radius: ${tokens.radius.card / 16}rem;
${spacing}
  --lin-size-brand-mark: ${tokens.size.brandMark / 16}rem;
  --lin-size-primary-button-min-height: ${tokens.size.primaryButtonMinimumHeight / 16}rem;
  --lin-size-content-max-width: ${tokens.size.contentMaximumWidth / 16}rem;
}

@media (prefers-color-scheme: dark) {
  :root {
${semantic("dark", "    ")}
  }
}
`;
}

function generateH5CSS() {
  const ramps = Object.entries(tokens.color.cssRamp)
    .flatMap(([family, ramp]) =>
      Object.entries(ramp).map(([step, value]) => `  --${family}-${step}: ${value};`),
    )
    .join("\n");
  const readerTheme = (mode, indent = "  ") => {
    const semantic = tokens.color.semantic[mode];
    return [
      ["page", semantic.background],
      ["text", semantic.foreground],
      ["body-text", semantic.foreground],
      ["muted-text", semantic.mutedForeground],
      ["rule", semantic.border],
      ["quote-bg", semantic.muted],
    ]
      .map(
        ([name, reference]) =>
          `${indent}--${name}: ${cssColor(reference).replaceAll("--color-", "--")};`,
      )
      .join("\n");
  };

  return `/* ${notice} */
:root {
  color-scheme: light dark;
${ramps}
${readerTheme("light")}
  --reader-font-scale: 1;
}

@media (prefers-color-scheme: dark) {
  :root {
${readerTheme("dark", "    ")}
  }
}

[data-theme="light"] {
  color-scheme: light;
${readerTheme("light")}
}

[data-theme="dark"] {
  color-scheme: dark;
${readerTheme("dark")}
}
`;
}

function generateHarmonyDimensions() {
  const values = Object.entries({
    ...Object.fromEntries(
      Object.entries(tokens.spacing).map(([key, value]) => [
        `spacing${upperFirst(safeName(key))}`,
        value,
      ]),
    ),
    ...Object.fromEntries(
      Object.entries(tokens.radius).map(([key, value]) => [`radius${upperFirst(key)}`, value]),
    ),
    ...Object.fromEntries(
      Object.entries(tokens.size).map(([key, value]) => [`size${upperFirst(key)}`, value]),
    ),
  })
    .map(([key, value]) => `  static readonly ${key}: number = ${value};`)
    .join("\n");
  return `// ${notice}
export class DesignTokens {
${values}
}
`;
}

const outputs = new Map([
  [
    "apps/android/app/src/main/kotlin/com/linonward/app/designsystem/BrandColors.kt",
    generateAndroid(),
  ],
  ["apps/ios/LinOnward/DesignSystem/DesignTokens.generated.swift", generateIOS()],
  ["apps/harmony/entry/src/main/resources/base/element/color.json", harmonyColors("light")],
  ["apps/harmony/entry/src/main/resources/dark/element/color.json", harmonyColors("dark")],
  [
    "apps/harmony/entry/src/main/ets/designsystem/DesignTokens.generated.ets",
    generateHarmonyDimensions(),
  ],
  ["apps/www/src/app/design-tokens.generated.css", generateWebCSS()],
  ["apps/web/src/app/design-tokens.generated.css", generateWebCSS()],
  ["apps/h5/src/design-tokens.generated.css", generateH5CSS()],
]);

let drifted = false;
for (const [relativePath, expected] of outputs) {
  const destination = path.join(repositoryRoot, relativePath);
  if (checkOnly) {
    const actual = await readFile(destination, "utf8").catch(() => "");
    if (actual !== expected) {
      console.error(`${relativePath} is not generated from design/tokens.json`);
      drifted = true;
    }
  } else {
    await writeFile(destination, expected);
    console.log(`generated ${relativePath}`);
  }
}

if (drifted) {
  console.error("Run `pnpm design-tokens:generate` and commit the generated files.");
  process.exitCode = 1;
}
